workspace:
    base: /test
    path: code-review

services:
    web:
        image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
        environment:
            - DOCUMENT_ROOT=/test/code-review

pipeline:
    composer-install-lowest:
        group: prepare
        image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
        volumes:
            - /cache:/cache
        commands:
            # Perform a composer install to work around an issue where an update
            # without a lock file present affects the resolving of dependencies.
            # Todo: Remove the `composer install` when the composer bug is fixed.
            # Ref. https://github.com/composer/composer/issues/7542
            # Ref. https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
            - composer install --ansi --no-suggest --no-progress
            - composer update --prefer-lowest --ansi --no-suggest --no-progress
        when:
            matrix:
                COMPOSER_BOUNDARY: lowest

    composer-install-highest:
        group: prepare
        image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
        volumes:
            - /cache:/cache
        commands:
            - composer install --ansi --no-suggest --no-progress
        when:
            matrix:
                COMPOSER_BOUNDARY: highest

    grumphp:
        group: test
        image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
        commands:
            - ./vendor/bin/grumphp run

    phpunit:
        group: test
        image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
        commands:
            - ./vendor/bin/phpunit

matrix:
    COMPOSER_BOUNDARY:
        - lowest
        - highest
