clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: registry.fpfis.eu/drone-plugins/git
    when:
      event: [ deployment ]

workspace:
  base: /test
  path: code-review

services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    environment:
      - DOCUMENT_ROOT=/test/code-review
      - COMPOSERVER=--2

pipeline:
  composer-install:
    group: prepare
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION}-ci
    volumes:
      - /cache:/cache
    commands:
      - composer self-update --2
      - composer install --ansi

matrix:
  PHP_VERSION:
    - 8.1
    - 8.2
    - 8.3
